name: tests

on: push

jobs:
  build:
    name: unit-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install-requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements-dev.txt
          python3 -m pip install .

      - name: run-tests
        run: | 
          coverage run -m pytest test
          coverage xml
          coverage html
          genbadge coverage -i coverage.xml
